Content/Bosses/VitricBoss/NPCs.VitricBossCrystal.cs

cieros boss crystals were not synced for the cutscene
they weren't sending their startPos so the other clients were using some random values in place of them

boss crystal cutscene fix (should smooth vulnerability phase too)

---

Content/Tiles/Vitric/Temple/BossSpawnerHolder.cs

This is to fix the premium glass idol holder which previously would not drop the idol in multiplayer
changed the item summoning to a quickspawn which is mp compatible.

boss spawner holder mp fix

---

Content/Packets/SpawnNPCPacket.cs
Content/Pickups/AbilityPickupTile.cs

in multiplayer each client would create a local clientside version of the ability pickup, causing the player to ride random npcs that overwrite the clientside pickup if the player picked up the ability very quick after world load
should be better all around and more deterministic since the whoami is synced on all clients and server, also included a cooldown timer on the ability spawn so it wouldn't need to be checked every frame

Fix for ability pickup not spawning on server

---

Content/Abilities/AbilityHandler.cs
Content/Abilities/AbilityHelper.cs
Content/Bosses/VitricBoss/NPCs.VitricBoss.Attacks.cs
Content/Bosses/VitricBoss/NPCs.VitricBoss.Cutscenes.cs
Content/Bosses/VitricBoss/NPCs.VitricBoss.cs
Content/CustomHooks/Mechanics.NoBuild.cs
Content/CustomHooks/Visuals.LightingBuffer.cs
Content/GUI/BootlegHealthbar.cs
Content/Items/BarrierDye/BaseBarrierDye.cs
Content/Items/BaseTypes/CursedAccessory.cs
Content/Items/Misc/Weapons.TwistSword.cs
Content/Items/Moonstone/Armors.Datsuzei.cs
Content/Items/Moonstone/Armors.MoonstoneArmor.cs
Content/Items/SteampunkSet/Weapons.Buzzsaw.cs
Core/ParticleSystem.cs
Core/StarlightPlayer.cs
Helpers/LightingBuffer.cs

This is to fix several bugs discovered during the larger multiplayer test.
fix for no build allowing hammering blocks
fix for buzzsaw unsafely typecasting
Cieros has added check to make sure player is not dead when selecting a random target
Cieros cutscenes modified to run for all players for logic and split out the clientside only portions to those inside arena
fix for twist sword crash and particle system crash after reloading mod
fix for fresh characters getting unlocked abilities after someone else obtains the ability in multiplayer + packet optimizations on world load for sharing unlock statuses
fix for black textures when in full screen
generally should have no effects on gameplay ouside of fixing the bugs. cutscene fixes were implemented with doing a sort of smear of the globaltime …

Bug fixes from large multiplayer test

---

Content/Bosses/VitricBoss/NPCs.VitricBoss.Attacks.cs
Content/Bosses/VitricBoss/NPCs.VitricBoss.Cutscenes.cs
Content/Bosses/VitricBoss/NPCs.VitricBoss.cs
Content/Bosses/VitricBoss/NPCs.VitricBossCrystal.cs
Content/CustomHooks/Visuals.PlayerTarget.cs
Content/Items/Breacher/Weapons.Scrapshot.cs
Content/Items/Vitric/Weapons.VitricHook.cs
Content/NPCs/BaseTypes/GravityOrbTest.cs
Content/Packets/CeirosCrystalPacket.cs
Core/StarlightPlayer.cs

This is to fix issues from the previous demo build.
fixes players getting stuck rotated after using scraphook or ripshatter
modifed player render target to use full rotation
improvements to Cieros and crystal movement sync
better visual effect sync of smashing crystals for the health gates
Cieros instantly retargets when targetted player dies
fix for Cieros getting invulnerable rarely in mp from being set to friendly
only notable consequence is that player.fullrotation is being reset in reset effects from now on

More mp fixes

---

Content/Bosses/VitricBoss/NPCs.ArenaBacks.cs
Content/CustomHooks/Mechanics.MovingPlatforms.cs

this enables hooks to give players their jump again when they stop at the hook while the platform is moving. previously if the platform was moving hooking to it would not give the player a jump. this is to bring it more in line with how platforms are expected to function
this is done through checking if the player has a single hook active and if so, checking if it and the player are all intersecting hit boxes with the moving platform and if so, sets the players position to the correct hook position directly so they will be able to zero out their Y velocity for the frame and get their jump back. Maybe a rework into an advanced version in the future that checks if the player has approximately reached the center of multiple hooks that are on moving platforms to give jump back in that …

hooks give jump back on moving platforms

---

Content/Bosses/VitricBoss/NPCs.VitricBoss.Cutscenes.cs
Content/CustomHooks/Mechanics.MovingPlatforms.cs
Content/Tiles/Vitric/VitricBossAltar.cs
Content/Tiles/Vitric/VitricOre.cs
Core/Dummy.cs

this is to fix a few remaining mp bugs found for the demo
improved returning jump for downwards moving platforms
arena bottom no longer spawns client side -- fixes minor bug where the bottom could proc more than once
fixes to dummy deletion detection -- wtf relogic why is there an "active" field for tiles that only applies to mp when its sending packets for the tile changes anyway????
should be no consequences to these changes

minor mp fixes.

---

Content/Items/BaseTypes/SmartAccessory.cs
Content/Items/Misc/Accessories.TestSimulator.cs

SmartAccessory now has a virtual ChildTypes property, which allows for an accessory to simulate the effects of another SmartAccessory. This is done via a list in a ModPlayer, which stores a list of "simulacrums", with each having a list of parents. Simulacrums act as if they're equipped, if all of a simulacrum's parents are gone, it dies. You cant equip a child with its parent or a parent with any of it's children.
No
No, this is largely finished and includes usage examples already.

Accessory simulation

---

Content/Items/Misc/Weapons.DualCross.cs

What is being fixed or optimized? Is there an associated issue?
Dual cross now correctly adds the damage of the ammo to the weapon, instead of multiplying them (additionally cleaned up code for dual cross). No associated issue
What are the implementation specifics of this change? Are there any consequences?
Instead of simply adding to the StatModifider damage in PickAmmo, it now adds to damage.Flat.

Dual cross damage fix + cleanup

---

Core/StarlightPlayer.cs

Fixes the lighting buffer being sized incorrectly on initial world load sometimes, causing buggy visual artifacts when it is used. This is done by forcing a resize of the buffer when the player joins the world.

Added forced buffer size refresh on world enter

---

Content/WorldGeneration/GenerateDropPods.cs

Drop pods no longer crash worldgen. The crash was due to Tmod making WorldGen.floatingIslandHouseX public, so instead of grabbing it via reflection, I could just grab it directly

Fixed drop pods crashing worldgen

---

Content/Items/Misc/Weapons.Sling.cs

Whenever the sling is used without ammo, the CanUseItem() hook runs, which then sets Item.noUseGraphic to true, making the holdStyle not appear. This fix makes this not happen anymore.

Made sling not bug out when used without ammo

---

Content/Items/Breacher/Weapons.FlareBreacher.cs

https://github.com/ProjectStarlight/StarlightRiver/issues/267
value returned in the HoldOffset hook of the flare breacher item has been changed from -10 to +2

adjusted flare breacher offset

---

Content/Items/UndergroundTemple/Weapons.RuneStaff.cs

https://github.com/ProjectStarlight/StarlightRiver/issues/268
Rune staff corrected to use cloning, sets item animation while held so the game continues to consider the item held

rune staff now behaves properly while held in cursor

---

Core/GrazePlayer.cs

Stops Graze logic from running whilst player is dead, fixing a few bugs.

player dead fix

---

Content/NPCs/Forest/Blover.cs

**What is being fixed or optimized? Is there an associated issue?**
Based on [this trello card](https://trello.com/c/7wHVFIm9/155-blover-change), Blover kb is reduced when the player has knockback resist. Wasn't sure if this should be completely disabled or not. Open to changes.
**What are the implementation specifics of this change? Are there any consequences?**
Disables Blover knockback when `Player.noKnockback` is true i.e. when the player has a cobalt shield equipped. No consequences that I am aware of.

 Disable Blover knockback for players with knockback reduction

---

Content/WorldGeneration/GenerateForest.cs

Simply makes bushes not generate below floating islands in non grassy areas, like snow or deserts. Also makes them not able to generate in said areas ABOVE grass, such as if another mod (or that one seed) generate grass underground
Shouldn't have any other ramifications

Made bushes not generate below floating islands

---

Content/CustomHooks/Content.PrehardmodeWarning.cs

Follows https://trello.com/c/ouKj3c9G/141-end-of-phm-warning-1 to a T.
Nothing left to do, except maybe review the text itself.

End of prehardmode warning

---

Core/Systems/MetaballSystem/MetaballSystem.cs

As the title says, this fixes an occaisional crash where drawing and loading metaball actors would happen at the same, causing a crash.
The only ramification I can think of is this fix means we can't have metaballs on the main menu, but that seems like a non issue.

Fixed metaball system crashing game occaisionally during bootup

---

Content/Items/Misc/Weapons.TwistSword.cs
Core/Systems/NPCUpgradeSystem/NPCUpgradeSystem.cs

This fixes the resource bar for the twisted great sword, fixes it having multiple projectiles when auto-reuse is on, adds the twisted greatsword's animation and upwards acceleration scaling off of melee attack speed. fixes packet overflow for npc upgrade system which prevented some worlds being loaded in multiplayer.

#329 twist sword fix

---

Content/Items/Misc/Weapons.MagmaGun.cs

Fixed and optimizes the magma gun to create it's dummy projectile while firing if one does not exist, and to not check it's dummy extraneously.

Optimized and fixed magmagun

---

Core/Systems/AuroraWaterSystem/AuroraWaterSystem.cs
Core/Systems/MetaballSystem/MetaballActor.cs
Core/Systems/MetaballSystem/MetaballSystem.cs

This should fix the load crash when metaballs get added to the collection while its trying to be iterated over

Added semaphore for metaball collection

---

Content/Items/Misc/Accessories.Corpseflower.cs

yeah pretty much just some fixes that I noticed while messing around with the corpseflower some more. totalDamage is multiplied by 1/3 so the dot number appears more even if you are continually attacking

im stupid and forget to test things :)

---

Content/Items/BuriedArtifacts/Weapons.AztecDeathSaxophone.cs

prevents hit/kill particles from spawning if you dont have the sax in your inventory

Aztec Death Sax fix

---

Content/Bosses/SquidBoss/NPCs.ArenaBlocker.cs

Fixed a bug where the Auroracle ArenaBlocker could be moved by Fae Whip.
No associated issue (honestly it was easier to fix than write an issue)
1 new line

Fixed a bug where the Auroracle ArenaBlocker could be moved by Fae Whip

---

Content/Items/Debug.cs
Content/WorldGeneration/GenerateBigTrees.cs
Content/WorldGeneration/GenerateVitric.cs

This PR touches up the vitric desert generation, and moves it to the center of the desert as opposed to the bottom. It adds two new features, a small dome at the top near the entrance for clearance, and spiked tunnel to the right for access to content that may be below the desert since it is now in the middle.

Vitric gen

---

Core/WalkableCrystal.cs

The `TileObjectData` for `VitricCrystals` had a `CoordinateWidth` and by extension a `CoordinateFullWidth` of 0 which would cause `TileObjectData.GetTileData` to throw a `DivideByZeroException`
No
`CoordinateWidth` was set to 16.
I don't think so

Fix CoordinateWidth for VitricCrystals

---

.gitignore

Should reduce the amount of merge conflicts from it getting generated every time
VS seemed to be acting weird about this getting removed and not treating it like it is but I'm nearly 100% confident that the gitignore itself is correct and its just VS being VS

add Localization/en-US.hjson to gitignore to cutdown on commit merge conflicts

---

Content/Bestiary/SLRSpawnConditions.cs
Content/CustomHooks/Visuals.CharacterSelectAddons.cs
Content/CustomHooks/Visuals.VitricBackground.cs
Content/CustomHooks/Visuals.WaterAddonHandler.cs
Content/Items/BaseTypes/CursedAccessory.cs
Content/Lavas/LavaLoader.cs
Content/NPCs/Actors/StarlightWaterActor.cs
Content/Physics/VerletChain.cs
Core/Loaders/ArmorEnchantLoader.cs
Core/Loaders/DyeLoader.cs
Core/Loaders/TileDrawOverLoader.cs
Core/PlayerTicker.cs
Core/Systems/CutawaySystem/CutawayHook.cs
Core/Systems/ForegroundSystem/ForegroundSystem.cs
Core/Systems/MetaballSystem/MetaballSystem.cs
Core/Systems/PersistentDataSystem/PersistentDataStore.cs
StarlightRiver.cs

This PR adds some safety checks to various unloading methods to ensure we dont try to unload already null data, causing a nasty crash.

Unload null coalesce

---

Content/GUI/CookingUI.cs
Content/Items/Food/Ingredient.cs
Content/Items/Food/Meal.cs
Content/Tiles/Crafting/CookStation.cs
PATCH_NOTES.txt

fixes cooking in multiplayer as well as adding a fewUI QoL enhancements and autoclosing the UI if the player wanders too far
Shift left click in cooking UI quick removes from the slot and places into the chefs bag or inventory if no chef bag
right clicking in cooking UI picks up one at a time
could implement other hotkeys but these were the ones that felt the most natural to me and others seemed kind of off or would be very difficult due to chests

Mp cooking

---

Content/CustomHooks/Mechanics.MouseSlotUseableInator.cs
PATCH_NOTES.txt

This fixes the auto-select issue reported #665.
Completely disables the broken IL edit in question since it has no use as far as I can tell.

fix for auto select

---

Content/Tiles/Vitric/DestructableGlass.cs
Content/Tiles/Vitric/Temple/GearPuzzle/GearTile.cs
Core/Systems/DummyTileSystem/Dummy.cs
Core/Systems/DummyTileSystem/DummyTile.cs
PATCH_NOTES.txt

This fixes a few issues found with dummies in multiplayer. most specifically around late joins to a world now can receive dummy info and clients no longer send netupdates for the dummies.  Server now tells clients to delete dummies when they are set inactive

hardened dummy system for multiplayer

---

Content/Tiles/Vitric/Temple/GearPuzzle/GearTile.cs
Content/Tiles/Vitric/Temple/VitricTempleWall.cs

Fixes 2 of the most dire memory consumers in the mod. Note, we really should move to caching any and all textures used for drawing as the string manipulation on Request is really memory hungry, ouch! Best thing is probably moving any instances of Request to be a static Asset in the file and then getting Asset.Value to draw dynamically. Probably automatable with a clever script (Get AI involved?)

Fix major memory drains

---

Content/CustomHooks/Visuals.ReflectionTarget.cs
Core/Systems/ScreenTargetSystem/ScreenTargetHandler.cs
PATCH_NOTES.txt

guessing these were broken during the migration to the new rendertarget system. fixes some issues with reflections and cutaways especially for inverted gravity

fixes for cutaway and reflection target inverted gravity rendering

---

Properties/launchSettings.json

Fixed not being able to build the solution using editors, such as JetBrains' Rider, which need the dotnet path to include the '.exe' extension in order to be recognized.
Relevant TML PR that fixed this issue:
tModLoader/tModLoader#3944

Updated dotnet path to support editors like Rider

---

Content/Items/Dungeon/Weapons.ThousandthDegree.cs

The sprite used for the Thousandth Degree projectile was the Thousandth Degree itself, not the accompanying wheel. I noticed this behaviour when testing the weapon itself and saw that there's an issue for it: #745 
I replaced `ThousandthDegreeProjectile` usages in ThousandthDegreeProjectileFired with `ThousandthDegreeProjectileFired`. See changed files and commits for details.

Fixed Thousandth Degree wheel sprite

---

Content/Buffs/CoughDropsBuff.cs
Content/Items/Misc/Accessories.CoughDrops.cs

ba6f4918418e004f6b6953761d10f3d367cebb6f, f5a86aaba6786c17a1e4ff2fde20d7d4d4f8766a: Made the Cough Drops buff only activate if the removed debuff displays the duration and can be removed by the nurse. This mostly fixes issue #445.
c22c20a68c0fb4e25effe54b4240b403f889f6c5: Reintroduced 15% additive damage buff to Cough Drops debuff.

Improved Cough Drops proc behaviour and added damage buff

---

Content/Bosses/GlassMiniboss/NPCs.Glassweaver.cs
Content/Bosses/SquidBoss/NPCs.SquidBoss.Cutscenes.cs
Content/Bosses/VitricBoss/NPCs.VitricBoss.Cutscenes.cs
Content/GUI/TextCard.cs
Content/Items/Debug.cs
Content/NPCs/Starlight/Crow.cs
Content/Pickups/ForbiddenWindsPickup.cs
Content/Pickups/StaminaShard.cs

Maintinence updates for the text card to untie it from abilities and hopefully fix a weird bug where people see it fail to dissappear

Text card updates

---

Core/Systems/CutawaySystem/CutawayHandler.cs
Core/Systems/CutawaySystem/CutawayHook.cs
PATCH_NOTES.txt

Adds a mod.call safety check for subworlds from subworld library to prevent the addition and rendering of cutaways that should not be present while in subworlds.
fixes https://github.com/ProjectStarlight/StarlightRiver/issues/782

Prevent cutaways in subworlds

---

Compat/Wikithis/WikithisWrapper.cs
StarlightRiver.cs

Support for [Wikithis](https://steamcommunity.com/sharedfiles/filedetails/?id=2832487441&searchtext=wikithis) such that you can however your cursor over any Starlight River item and press a configured button to swiftly open the corresponding wiki.gg page.
This was based on the suggestion by [TheCrossBoy](https://github.com/TheCrossBoy) in #773, where [ScalarVector1](https://github.com/ScalarVector1) approved of the compatibility. After some brief testing it feels like a good QoL improvement to have.
The implementation adds another wrapper for Wikithis to have a weak reference to the calls necessary to set it up, however, I'm not sure if there's a more appropriate location to perform this setup call, as it's currently done in `PostSetupContent`.

Support Wikithis

---

Core/Loaders/TileLoading/FurnitureLoader.cs

Fixes the generic door classes in `FurnitureLoader` to use the appropriate cursor item icon and makes the open door variants drop their corresponding item. Related issue: #512
I used `RegisterItemDrop` in order to fix the open door drop, and I fixed the `cursorItemIconID` being invalid which was why the player was freezing in the past when hovering their cursor over the door before.

Fix Vitric door
