- Content/Configs/AudioConfig.cs
- Content/Configs/GUIConfig.cs
- Content/Configs/GraphicsConfig.cs
- Content/CustomHooks/Audio.CustomInventorySounds.cs
- Content/CustomHooks/Mechanics.SoulboundItemRestrictions.cs
- Content/CustomHooks/Visuals.PlayerTarget.cs
- Content/CustomHooks/Visuals.WaterAddonHandler.cs
- Content/GUI/Stamina.cs
- Content/Lavas/LavaStyle.cs
- Core/DateChanges.cs
- Core/DummyTile.cs
- Core/ParticleSystem.cs
- Core/StarlightPlayer.cs
- Core/WindowForm.cs
- Core/WindowFormHandler.cs
- Helpers/LightingBuffer.cs
This is to fix the mod being unable to be loaded on linux or MacOS. As well as fix an issue where the game crashed when reloading the mod without entering a world first.
This is through changing the Soulbound IL edit to use the correct arguments, The water addon IL and inventory sound ILs were changed so that the arguments that later expressions needed are kept on the stack / added back to the stack since linux checks unconditional branches.
Did not test if this fixes it for Mac as well but assuming that mac and linux had the same issues it should be fixed.
> Fna support

- Content/Items/Beach/Accessories.SeaglassRing.cs
We recommend you use one of our pull request templates for ease of review. Pull Requests which ignore the template or the other guidelines in general may be closed.
[PR Template for bug fixes or optimizations](https://github.com/ProjectStarlight/StarlightRiver/blob/master/PR_BUG_FIXES.md)
template=PR_BUG_FIXES.md  
[PR Template for additions (Be sure to have consulted the devs first)](https://github.com/ProjectStarlight/StarlightRiver/blob/master/PR_CONTENT_ADDITIONS.md)
template=PR_CONTENT_ADDITIONS.md
Please make sure you follow the style guide: https://github.com/ProjectStarlight/StarlightRiver/blob/master/STYLE_GUIDE.md
> Seaglass sparkles

- Content/Items/Breacher/Accessories.ReactivePlating.cs
- Content/Items/Misc/Weapons.Sandscript.cs
- Content/Items/Moonstone/Materials.Moonstone.cs
- Content/Items/SteampunkSet/Mounts.Cogwheel.cs
- Content/Items/Vitric/IgnitionGauntlets/Weapons.IgnitionGauntlets.cs
- Core/LearnableRecipie.cs
- StarlightRiver.cs
ported to the august freeze of tModLoader
no
no
> August porting

- Content/Items/Beach/Accessories.SeaglassRing.cs
What are the specifics of what is being added?
Seaglass ring now has a 1/15 chance of being rare loot if fishing in the ocean
Is there an associated suggestion or dev server #code-needed post? How well does this PR follow it?
https://trello.com/c/lS1O0zsG/293-make-seaglass-ring-able-to-be-fished-up
To a T
Is there anything left to be done in this addition?
No
> Made seaglass ring fishable

- Content/Items/Breacher/Ammo.Scrappod.cs
- Content/Items/Vitric/Ammo.VitricBullet.cs
Made both of the bullet projectiles use aiStyle 1 and AIType of ProjectileID.Bullet, and fixed some inconsistencies in spawning / breaking the vitric crystal projectile.
> Some bugfix / misc changes

- Content/Items/Misc/Accessories.PandorasShield.cs
> fixed pandoras shield giving unlimited barrier against some attacks

- Content/Items/Permafrost/Weapons.AuroraBell.cs
https://github.com/ProjectStarlight/StarlightRiver/issues/261
Change tooltip to remove reported typo
> corrected typo in aurora bell tooltip

- Content/NPCs/Forest/Blover.cs
Blover now takes half a second to wind up it's blowing ability, making it easier to fight
> Blover tweak

- Content/Prefixes/Accessory/BarrierPrefixes.cs
Adds 4 Barrier prefixes for accessories
> Added Barrier Prefixes

- Content/NPCs/TownModifications/TruffleShopAdditions.cs
- Content/Tiles/Mushroom/JellyShroom.cs
- Content/WorldGeneration/GenerateBouncyMushrooms.cs
- Content/WorldGeneration/WorldgenWorld.cs
This PR makes jellyshrooms generate, as well as doing the following to jellyshrooms
-Adjusting their mining sound
-Adjusting the amount of dust they spawn
-Making them drop jellyshroom items
> Bouncy mushroom generation

- Content/Items/Misc/Accessories.Cheapshakes.cs
What are the specifics of what is being added?
A refactor to the Cheapskates accessory
Is there an associated suggestion or dev server #code-needed post? How well does this PR follow it?
https://trello.com/c/XGy9BI4T/149-cheapskates-2 follows it perfectly
Is there anything left to be done in this addition?
not that I can think of
> Cheapskates Finished

- Content/Items/Permafrost/Accessories.BookOfFrost.cs
Book of frost now only activates if you have the book equipped
> fixed book of frost

- Content/Archaeology/ArchaeologyHandler.cs
- Content/Archaeology/Artifact.cs
Fixed bug where artifacts didn't draw by moving it to a different detour. Has no ingame issues as far as I can tell.
> Working artifact fix

- Content/Items/Misc/Accessories.CasualMirror.cs
Causal mirror is not named correctly and doesn't have a gap in it's tooltip
> Fixed causal mirror

- Content/CustomHooks/Visuals.PlayerTarget.cs
- Content/Items/BarrierDye/BaseBarrierDye.cs
- Content/Items/BarrierDye/MoonstoneBarrierDye.cs
- Content/Items/BarrierDye/VitricBossBarrierDye.cs
- Content/Items/BaseTypes/SmartAccessory.cs
- Core/DistortionPointHandler.cs
- Core/Loaders/DyeLoader.cs
- Core/Systems/BarrierSystem/LifeUITextHook.cs
- Core/Systems/BarrierSystem/PlayerRadarBarrierHook.cs
- Core/Systems/KeywordSystem/KeywordScanner.cs
This is primarily a lot of polish for the barrier system. Also comes with mp compat for smart accessory and the bare minimum to load the mod in multiplayer
Should be consequence free though there is an IL edit added
> Barrier System polish + bare minimum to load mod in multiplayer

- Content/WorldGeneration/SurfaceItemPass.cs
This fixes https://github.com/ProjectStarlight/StarlightRiver/issues/192 by correcting an error in the 1.4 port
> Fixed seaglass gen (fixes https://github.com/ProjectStarlight/StarlightRiver/issues/192)

- Content/Bosses/VitricBoss/NPCs.VitricBossPlatforms.cs
- Content/CustomHooks/Mechanics.MovingPlatforms.cs
- Content/NPCs/BaseTypes/MovingPlatform.cs
Fix for https://github.com/ProjectStarlight/StarlightRiver/issues/166 which should add full debuff immunity to moving platforms
> Fix moving platforms being debuffable

- Content/Items/Misc/Weapons.RadculasRapier.cs
forgot to change the buff time from when I was testing the dash.
> Radcula Fix

- Content/GUI/BarrierDyeSlot.cs
- Core/Loaders/UILoading/UILoader.cs
- Core/Systems/ScreenTargetSystem/ScreenTarget.cs
- Core/Systems/ScreenTargetSystem/ScreenTargetHandler.cs
This fixes the mod from being unable to be loaded in multiplayer and for clicks on our UI elements not being interactable at first until tabbing out
still could use the rest of the UI elements getting a makeover with moving the overrides to event listeners
> render target for mp + partial fix for clicks not registering at first

- Content/Bestiary/ModBiomeSpawnCondition.cs
- Content/GUI/BarrierDyeSlot.cs
- Content/GUI/BossBarOverlay.cs
- Content/GUI/ChatboxOverUI.cs
- Content/GUI/ChefBagUI.cs
- Content/GUI/Codex.cs
- Content/GUI/Collection.cs
- Content/GUI/CombatMountInfo.cs
- Content/GUI/CookingUI.cs
- Content/GUI/EnchantmentMenu.cs
- Content/GUI/ExtraDefenseStats.cs
- Content/GUI/Infusion.cs
- Content/GUI/InfusionMaker.cs
- Content/GUI/KeyInventory.cs
- Content/GUI/LootUI.cs
- Content/GUI/MasterDeathTicker.cs
- Content/GUI/MessageBox.cs
- Content/GUI/RichTextBox.cs
- Content/GUI/Stamina.cs
- Content/GUI/TextCard.cs
- Content/GUI/TownQuestList.cs
- Content/Items/Misc/Accessories.StaminaUp.cs
- Content/Items/Misc/CursedAccessories.HungryStomach.cs
- Core/Loaders/UILoading/SmartUIElement.cs
- Core/Loaders/UILoading/UILoader.cs
This PR implements the SmartUIElement class, a safe wrapper around UIElement that ensures that the various click and update methods work harmoniously with event listeners. It also copies these over to SmartUIState and includes some helpers in SmartUIState to ensure element appending logic is consistent across the UI code.
> UI rework and refactor

- Content/Abilities/Faewhip/TestWhipInfusion.cs
- Content/Alchemy/MixingStick.cs
- Content/Items/BarrierDye/BaseBarrierDye.cs
- Content/Items/Example/ExampleCombatMount.cs
- Content/Items/Misc/Weapons.CutlassBus.cs
- Content/Pickups/FaeflamePickup.cs
- Content/Pickups/ForbiddenWindsPickup.cs
- Content/Pickups/StaminaShard.cs
- Content/Tiles/Permafrost/AuroraBrick.cs
- Content/Tiles/VerletBanner.cs
- Content/Tiles/Vitric/RedBannerShort.cs
- Content/Tiles/Vitric/Temple/VitricTempleWall.cs
- Content/Tiles/Vitric/VitricVases.cs
Marks items that, to my best judgment, appear to be debug items, with [SLRDebug]. Please double-check to make sure I haven't incorrectly labelled anything.
> Marking debug items with [SLRDebug]

- Content/Alchemy/Cauldron.cs
- Content/Items/BuriedArtifacts/Artifacts.Totems.cs
- Content/Items/Desert/Weapons.Sandscript.cs
- Content/Items/Misc/Weapons.ImpactSMG.cs
- Content/Tiles/Crafting/CookStation.cs
- Content/Tiles/Crafting/Infuser.cs
- Content/Tiles/Desert/AnkhChest.cs
- Content/Tiles/Forest/ForestBerryBush.cs
- Content/Tiles/Forest/SlimeberryBush.cs
- Content/Tiles/Interactive/Bounce.cs
- Content/Tiles/Mushroom/JellyShroom.cs
- Content/Tiles/Paintings/AuroraclePainting.cs
- Content/Tiles/Paintings/EggCodexPainting.cs
- Content/Tiles/Paintings/RatKingPainting.cs
- Content/Tiles/Trophies/AuroracleTrophy.cs
- Content/Tiles/Trophies/CeirosTrophy.cs
- Content/Tiles/Underground/HotspringFountain.cs
- Localization/en-US.hjson
Removes several KillMultiTile hooks that were causing duplicate item drops when tiles were broken
> KillMultiTIle hook removals

- Content/GUI/BossRushMenu.cs
- Content/GUI/BossRushScore.cs
- Content/GUI/MasterDeathTicker.cs
- Core/Systems/BossRushSystem/BossRushGUIHack.cs
- Core/Systems/BossRushSystem/BossRushNPC.cs
- Core/Systems/BossRushSystem/BossRushPlayer.cs
- Core/Systems/BossRushSystem/BossRushSystem.cs
This PR adds the final score screen to boss rush and fixes some issues with it
> Boss rush tuning

- Content/Items/Misc/Accessories.SpearBook.cs
- Content/Items/Misc/Accessories.SwordBook.cs
- Localization/en-US.hjson
This PR updates the mantis technique to be up to spec, including adding the parry functionality and supporting projectile weapons
> Mantis Technique

- Content/Abilities/Hint/Hint.cs
- Content/Backgrounds/StarlightRiverBg.cs
- Content/Events/StarlightEvent.cs
- Content/NPCs/Starlight/Crow.cs
- Content/NPCs/Starlight/CrowCutsceneOne.cs
- Core/Systems/CutsceneSystem/Cutscene.cs
- Core/Systems/CutsceneSystem/CutscenePlayer.cs
- Localization/en-US.hjson
This PR implements a player-authoritative cutscene system, that is properly net synced, as well as fixes the alican event bug in multiplayer.
> Alican cutscene fix

- Content/Items/Misc/Weapons.FryingPan.cs
- Content/Items/Utility/ArmorBag.cs
- Content/Items/Vitric/Tools.VitricHamaxe.cs
- Content/Items/Vitric/Tools.VitricPick.cs
- Content/NPCs/Dungeon/CrescentCaster.cs
- Content/Tiles/CrashTech/CrashPod.cs
- Content/WorldGeneration/GenerateBigTrees.cs
- Content/WorldGeneration/GenerateDropPods.cs
- Content/WorldGeneration/GenerateForest.cs
- Core/Systems/AuroraWaterSystem/SwimPlayer.cs
- Core/Systems/CombatMountSystem/CombatMountPlayer.cs
- Localization/en-US.hjson
- PATCH_NOTES.txt
A PR consisting of a few smaller fixes for some of the more apparent bugs in the mod, check patchnotes diff for a full list
> Misc. Fixes

- description.txt
This adds TripleFate to the description.txt as a developer
> Add TripleFate to the description

- .github/ISSUE_TEMPLATE/bug_report.md
We recommend you use one of our pull request templates for ease of review. Pull Requests which ignore the template or the other guidelines in general may be closed.
[PR Template for bug fixes or optimizations](https://github.com/ProjectStarlight/StarlightRiver/blob/master/PR_BUG_FIXES.md)
template=PR_BUG_FIXES.md  
[PR Template for additions (Be sure to have consulted the devs first)](https://github.com/ProjectStarlight/StarlightRiver/blob/master/PR_CONTENT_ADDITIONS.md)
template=PR_CONTENT_ADDITIONS.md
Please make sure you follow the style guide: https://github.com/ProjectStarlight/StarlightRiver/blob/master/STYLE_GUIDE.md
> update bug report template to new log file path

- Content/Items/Permafrost/Weapons.Tentalance.cs
fixes merge conflict but that broke tentalance
> fix merge conflict bug that slipped through

- Content/Bosses/SquidBoss/NPCs.ArenaActor.cs
- Content/Bosses/SquidBoss/NPCs.IcePlatform.cs
- Content/Bosses/SquidBoss/NPCs.SquidBoss.cs
- Content/Bosses/VitricBoss/NPCs.ArenaBacks.cs
- Content/Items/ArmsDealer/Weapons.DefenseSystem.cs
- Content/Items/Gravedigger/Weapons.Gluttony.cs
- Content/Items/Misc/Weapons.HeartStatueSentry.cs
- Content/NPCs/BaseTypes/MovingPlatform.cs
- Content/NPCs/Vitric/Gauntlet/FlyingGruntConstruct.cs
- Content/NPCs/Vitric/Gauntlet/FlyingPelterConstruct.cs
- Content/NPCs/Vitric/Gauntlet/GruntConstruct.cs
- Content/NPCs/Vitric/Gauntlet/JuggernautConstruct.cs
- Content/NPCs/Vitric/Gauntlet/PelterConstruct.cs
- Content/NPCs/Vitric/Gauntlet/ShieldConstruct.cs
- Content/Packets/PlayerHitPacket.cs
A small collection of MP fixes found during testing
> Mp quickfix

- PATCH_NOTES.txt
Adds a few missing patch notes from previous PRs
> Update patch notes

- Content/NPCs/Misc/LootWraith.cs
- PATCH_NOTES.txt
Polishes up patch notes and fixes loot wraith drops
> Update notes and drop pools

- Content/GUI/RichTextBox.cs
- Content/NPCs/Underground/GloomSlime.cs
- Content/Tiles/Vitric/Temple/GearPuzzle/DynamicGear.cs
- Content/Tiles/Vitric/Temple/GearPuzzle/GearPuzzleOrigin.cs
- Content/Tiles/Vitric/Temple/GearPuzzle/GearTile.cs
- Content/WorldGeneration/GenerateUndergroundTemples.cs
- Core/Systems/CutawaySystem/CutawayHook.cs
- Localization/en-US_Mods.StarlightRiver.hjson
- OldPatchNotes/0.2.0/0.2.6.txt
- PATCH_NOTES.txt
- StarlightRiver.csproj
- build.txt
Hotfix patch from previous version
> 0.2.6.2 fixes

- Content/CustomHooks/Content.AstralMeteor.cs
- Content/NPCs/Moonstone/AngryCrescent.cs
- PATCH_NOTES.txt
We recommend you use one of our pull request templates for ease of review. Pull Requests which ignore the template or the other guidelines in general may be closed.
[PR Template for bug fixes or optimizations](https://github.com/ProjectStarlight/StarlightRiver/blob/master/PR_BUG_FIXES.md)
template=PR_BUG_FIXES.md  
[PR Template for additions (Be sure to have consulted the devs first)](https://github.com/ProjectStarlight/StarlightRiver/blob/master/PR_CONTENT_ADDITIONS.md)
template=PR_CONTENT_ADDITIONS.md
Please make sure you follow the style guide: https://github.com/ProjectStarlight/StarlightRiver/blob/master/STYLE_GUIDE.md
> quick angry crescent mp compat hacks

- Content/WorldGeneration/GenerateForest.cs
- Localization/en-US_Mods.StarlightRiver.hjson
- PATCH_NOTES.txt
Fixes the issue with floating vegetables in worldgen
> Vegetable fix

- Content/Tiles/Vitric/Temple/GearPuzzle/DynamicGear.cs
- Content/Tiles/Vitric/Temple/LightPuzzle/Reflector.cs
- Core/Systems/DummyTileSystem/Dummy.cs
- PATCH_NOTES.txt
Makes the right click detection hitbox match the puzzle elements. Introduces a framework for right clicking custom sizes via dummies.
> Increased size of puzzle hitboxes

- Core/PrimitiveDrawing.cs
- PATCH_NOTES.txt
maybe needs an alternative system but disabling this does appear to stop the crashes
> fix trail crashes

- Content/Configs/GraphicsConfig.cs
- Core/Systems/DummyTileSystem/Dummy.cs
- Core/Systems/DummyTileSystem/DummySystem.cs
- Core/Systems/LightingSystem/LightingBuffer.cs
Remove bad lighting buffer option and fix subscriptions
> Remove bad config

- Content/CustomHooks/Mechanics.MovingPlatforms.cs
- Content/CustomHooks/Visuals.ReflectionTarget.cs
- Content/Items/Beach/Accessories.SaltCogs.cs
- Content/WorldGeneration/PermafrostGen.cs
- OldPatchNotes/0.2.0/0.2.8.txt
- PATCH_NOTES.txt
- build.txt
> Hotfix0284

- Content/WorldGeneration/GenerateForest.cs
- PATCH_NOTES.txt
Fixes https://github.com/ProjectStarlight/StarlightRiver/issues/727
> Forest midair generation fix

- Content/CustomHooks/Mechanics.NoBuild.cs
Whitelists the axe of regrowth for use in nobuild areas
fixes https://github.com/ProjectStarlight/StarlightRiver/issues/550
> Whitelist the axe of regrowth

- Content/Tiles/Forest/RiggedTree.cs
- Core/Systems/LightingSystem/LightingBuffer.cs
We recommend you use one of our pull request templates for ease of review. Pull Requests which ignore the template or the other guidelines in general may be closed.
[PR Template for bug fixes or optimizations](https://github.com/ProjectStarlight/StarlightRiver/blob/master/PR_BUG_FIXES.md)
template=PR_BUG_FIXES.md  
[PR Template for additions (Be sure to have consulted the devs first)](https://github.com/ProjectStarlight/StarlightRiver/blob/master/PR_CONTENT_ADDITIONS.md)
template=PR_CONTENT_ADDITIONS.md
Please make sure you follow the style guide: https://github.com/ProjectStarlight/StarlightRiver/blob/master/STYLE_GUIDE.md
> Fix tree popout
